'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sigal.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property alumno_alta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alumno_alta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property alumno_consulta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alumno_consulta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property asignacion_plan_materia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("asignacion_plan_materia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bullet_go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calificacion_cursada() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calificacion_cursada", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calificacion_cursada_alta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calificacion_cursada_alta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calificacion_cursada_consulta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calificacion_cursada_consulta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calificacion_final() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calificacion_final", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calificacion_final_alta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calificacion_final_alta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calificacion_final_consulta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calificacion_final_consulta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property correlatividad_alta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("correlatividad_alta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property correlatividad_consulta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("correlatividad_consulta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property correlatividades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("correlatividades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property curso_alta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("curso_alta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property curso_consulta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("curso_consulta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property curso_edicion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("curso_edicion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property glossymetal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("glossymetal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property informe_analitico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("informe_analitico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inscripcion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inscripcion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inscripcion_alta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inscripcion_alta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inscripcion_consulta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inscripcion_consulta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property materia_alta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("materia_alta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property materia_consulta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("materia_consulta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plan_alta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plan_alta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plan_consulta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plan_consulta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pmc_alta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pmc_alta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pmc_consulta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pmc_consulta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property salir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sigal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sigal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
